/*
 * Copyright 2026 Rodrigo Prestes Machado
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *     http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */
package dev.orion.twr.domain.model;

import java.util.Date;

import com.fasterxml.jackson.annotation.JsonIgnore;

/**
 * Base domain model that represents a message exchanged within a chat.
 *
 * @author Rodrigo Prestes Machado
 */
public abstract class Message {

    /**
     * Text content of the message.
     */
    private String message;

    /**
     * Chat session that contains this message.
     */
    private Chat chat;

    /**
     * Instant when the message was created.
     */
    private Date timestamp;

    /**
     * Returns the message text.
     *
     * @return the message content
     */
    public String getMessage() {
        return message;
    }

    /**
     * Sets the message text.
     *
     * @param message the message content to set
     */
    public void setMessage(String message) {
        this.message = message;
    }

    /**
     * Returns the chat that contains this message.
     *
     * @return the parent chat
     */
    @JsonIgnore
    public Chat getChat() {
        return chat;
    }

    /**
     * Sets the chat that contains this message.
     *
     * @param chat the parent chat to set
     */
    public void setChat(Chat chat) {
        this.chat = chat;
    }

    /**
     * Returns the message timestamp.
     *
     * @return the creation timestamp
     */
    public Date getTimestamp() {
        return timestamp;
    }

    /**
     * Sets the message timestamp.
     *
     * @param timestamp the creation timestamp to set
     */
    public void setTimestamp(Date timestamp) {
        this.timestamp = timestamp;
    }

    /**
     * Returns the role discriminator for this message ({@code "USER"} or
     * {@code "AGENT"}), serialized as-is by Jackson so the frontend can tell
     * apart user and assistant messages when loading persisted conversation
     * history (see {@code dev.orion.twr.adapter.in.rest.dto.MemoryResponse}).
     *
     * <p>Without this, every message in {@code GET /twr/memory} responses is
     * indistinguishable from the others once history is reloaded from
     * storage, since the concrete subtype otherwise carries no explicit
     * discriminator in the JSON payload.</p>
     *
     * @return {@code "USER"} for messages sent by the user, {@code "AGENT"}
     *         for replies generated by the assistant
     */
    public abstract String getType();

}
